### ISSUE TITLE
Slider widget publishes Servos message twice for one slider click

### ISSUE THREAD

**Issue by billmania** [billmania/roboquest_ui#159]
Clicking on a new position or moving the slider of a slider widget, which is configured with angle_deg and command_type 1, causes two Servos messages to be published to the /servos topic. It should publish only once.

It appears to publish once upon the click, if the slider value is changed. It then always publishes the current value on the release.

```
--
header:
  stamp:
    sec: 1737738476
    nanosec: 91000080
  frame_id: ''
servo0:
  angle_deg: 54
  angle_incr_deg: 0
  speed_dps: 0
  command_type: 1
--
header:
  stamp:
    sec: 1737738476
    nanosec: 200000047
  frame_id: ''
servo0:
  angle_deg: 54
  angle_incr_deg: 0
  speed_dps: 0
  command_type: 1
--
header:
  stamp:
    sec: 1737738480
    nanosec: 943000078
  frame_id: ''
servo0:
  angle_deg: 104
  angle_incr_deg: 0
  speed_dps: 0
  command_type: 1
--
header:
  stamp:
    sec: 1737738481
    nanosec: 35000085
  frame_id: ''
servo0:
  angle_deg: 104
  angle_incr_deg: 0
  speed_dps: 0
  command_type: 1
```
